extends Object

const DEFAULT_HORIZONTAL_ACCELERATION: float = 1500
const DEFAULT_MAX_HORIZONTAL_VELOCITY: float = 220
const DEFAULT_FRICTION_ACCELERATION: float = 2000

const DEFAULT_GRAVITATIONAL_ACCELERATION: float = 1800
const DEFAULT_JUMP_ACCELERATION: float = 500
const DEFAULT_MAX_VERTICAL_VELOCITY: float = 800

const DEFAULT_COYOTE_TIME_MS: int = 50
const DEFAULT_JUMPING_BUFFER_TIME_MS: int = 50
const DEFAULT_MAX_JUMPING_TIME_MS: int = 100
