extends Node

const DEFAULT_HORIZONTAL_ACCELERATION: float = 2500
const DEFAULT_MAX_HORIZONTAL_VELOCITY: float = 400
const DEFAULT_FRICTION_ACCELERATION: float = 2400

const DEFAULT_GRAVITATIONAL_ACCELERATION: float = 768.0
const DEFAULT_INCREASED_GRAVITATIONAL_ACCELERATION: float = 1536.0
const DEFAULT_INITIAL_JUMP_VELOCITY: float = 384.0

const DEFAULT_COYOTE_TIME_MS: int = 50
const DEFAULT_JUMPING_BUFFER_TIME_MS: int = 50
const DEFAULT_MAX_JUMPING_TIME_MS: int = 100
